name: toko_mart
description: TokoMart - Mobile Shopping App
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5

  # Navigation
  go_router: ^14.2.7

  # Networking
  dio: ^5.4.3+1
  # Connectivity
  connectivity_plus: ^6.0.0

  # Local Storage
  shared_preferences: ^2.5.5

  # Image picker
  image_picker: ^1.1.2

  # Runtime permissions
  permission_handler: ^11.3.1

  # Fonts
  google_fonts: ^6.2.1

  # Notifications
  flutter_local_notifications: ^17.0.0

  # Utilities
  flutter_dotenv: ^6.0.1
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  bloc_test: ^9.1.7
  mocktail: ^1.0.4
  patrol: ^4.7.1
  patrol_mcp: ^0.1.4
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/app_icon1.png"
  min_sdk_android: 21
  adaptive_icon_background: "#3D3DE8"
  adaptive_icon_foreground: "assets/images/app_icon1.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: PlusJakartaSans
      fonts:
        - asset: assets/fonts/PlusJakartaSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlusJakartaSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/PlusJakartaSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/PlusJakartaSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSans-ExtraBold.ttf
          weight: 800

patrol:
  app_name: TokoMart
  android:
    package_name: com.example.TokoMart
  ios:
    bundle_id: com.example.TokoMart
  macos:
    bundle_id: com.example.macos.TokoMart
